"""subscriptions + notif mod_id + edited_at

Revision ID: 0b57a5639ff9
Revises: 7f050552e7a2
Create Date: 2026-05-22 18:05:09.047666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b57a5639ff9'
down_revision: Union[str, Sequence[str], None] = '7f050552e7a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mod_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mod_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mod_id'], ['mods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mod_id', name='uq_modsub_user_mod')
    )
    op.create_index(op.f('ix_mod_subscriptions_mod_id'), 'mod_subscriptions', ['mod_id'], unique=False)
    op.create_index(op.f('ix_mod_subscriptions_user_id'), 'mod_subscriptions', ['user_id'], unique=False)
    op.add_column('forum_posts', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('forum_threads', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notifications', sa.Column('mod_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_notifications_mod_id'), 'notifications', ['mod_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'mods', ['mod_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_mod_id'), table_name='notifications')
    op.drop_column('notifications', 'mod_id')
    op.drop_column('forum_threads', 'edited_at')
    op.drop_column('forum_posts', 'edited_at')
    op.drop_index(op.f('ix_mod_subscriptions_user_id'), table_name='mod_subscriptions')
    op.drop_index(op.f('ix_mod_subscriptions_mod_id'), table_name='mod_subscriptions')
    op.drop_table('mod_subscriptions')
    # ### end Alembic commands ###
