"""mod_comments table

Revision ID: 0b899d72a3cd
Revises: fbd43a192589
Create Date: 2026-05-22 14:17:56.981278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b899d72a3cd'
down_revision: Union[str, Sequence[str], None] = 'fbd43a192589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mod_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mod_id', sa.BigInteger(), nullable=False),
    sa.Column('comment_id', sa.String(length=32), nullable=False),
    sa.Column('author_name', sa.String(length=128), nullable=True),
    sa.Column('author_profile_url', sa.Text(), nullable=True),
    sa.Column('author_avatar_url', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mod_id'], ['mods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id')
    )
    op.create_index(op.f('ix_mod_comments_mod_id'), 'mod_comments', ['mod_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mod_comments_mod_id'), table_name='mod_comments')
    op.drop_table('mod_comments')
    # ### end Alembic commands ###
