"""users + forum author_user_id

Revision ID: 23013bf7fd93
Revises: 552753c7e075
Create Date: 2026-05-22 16:11:07.015689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23013bf7fd93'
down_revision: Union[str, Sequence[str], None] = '552753c7e075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('google_sub', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_sub')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.add_column('forum_posts', sa.Column('author_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_forum_posts_author_user_id'), 'forum_posts', ['author_user_id'], unique=False)
    op.create_foreign_key(None, 'forum_posts', 'users', ['author_user_id'], ['id'], ondelete='SET NULL')
    op.add_column('forum_threads', sa.Column('author_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_forum_threads_author_user_id'), 'forum_threads', ['author_user_id'], unique=False)
    op.create_foreign_key(None, 'forum_threads', 'users', ['author_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forum_threads', type_='foreignkey')
    op.drop_index(op.f('ix_forum_threads_author_user_id'), table_name='forum_threads')
    op.drop_column('forum_threads', 'author_user_id')
    op.drop_constraint(None, 'forum_posts', type_='foreignkey')
    op.drop_index(op.f('ix_forum_posts_author_user_id'), table_name='forum_posts')
    op.drop_column('forum_posts', 'author_user_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
