"""mod_discussions + mod app_id/app_name

Revision ID: 47faa919aceb
Revises: da41129f54b6
Create Date: 2026-05-22 15:01:06.528412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47faa919aceb'
down_revision: Union[str, Sequence[str], None] = 'da41129f54b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mod_discussions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mod_id', sa.BigInteger(), nullable=False),
    sa.Column('thread_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body_preview', sa.Text(), nullable=True),
    sa.Column('author_name', sa.String(length=128), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=True),
    sa.Column('last_post_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_post_author', sa.String(length=128), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mod_id'], ['mods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    op.create_index(op.f('ix_mod_discussions_mod_id'), 'mod_discussions', ['mod_id'], unique=False)
    op.add_column('mods', sa.Column('app_id', sa.Integer(), nullable=True))
    op.add_column('mods', sa.Column('app_name', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_mods_app_id'), 'mods', ['app_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mods_app_id'), table_name='mods')
    op.drop_column('mods', 'app_name')
    op.drop_column('mods', 'app_id')
    op.drop_index(op.f('ix_mod_discussions_mod_id'), table_name='mod_discussions')
    op.drop_table('mod_discussions')
    # ### end Alembic commands ###
