"""forum threads + posts + upvotes

Revision ID: 552753c7e075
Revises: 47faa919aceb
Create Date: 2026-05-22 15:24:30.164455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '552753c7e075'
down_revision: Union[str, Sequence[str], None] = '47faa919aceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_threads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('body_raw', sa.Text(), nullable=False),
    sa.Column('mod_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('author_name', sa.String(length=64), nullable=False),
    sa.Column('author_token', sa.String(length=64), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_post_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mod_id'], ['mods.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_threads_author_token'), 'forum_threads', ['author_token'], unique=False)
    op.create_index(op.f('ix_forum_threads_mod_id'), 'forum_threads', ['mod_id'], unique=False)
    op.create_index(op.f('ix_forum_threads_slug'), 'forum_threads', ['slug'], unique=False)
    op.create_table('forum_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('body_raw', sa.Text(), nullable=False),
    sa.Column('author_name', sa.String(length=64), nullable=False),
    sa.Column('author_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['forum_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_posts_author_token'), 'forum_posts', ['author_token'], unique=False)
    op.create_index(op.f('ix_forum_posts_thread_id'), 'forum_posts', ['thread_id'], unique=False)
    op.create_table('forum_upvotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('voter_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['forum_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'voter_token', name='uq_upvote_thread_voter')
    )
    op.create_index(op.f('ix_forum_upvotes_thread_id'), 'forum_upvotes', ['thread_id'], unique=False)
    op.create_index(op.f('ix_forum_upvotes_voter_token'), 'forum_upvotes', ['voter_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forum_upvotes_voter_token'), table_name='forum_upvotes')
    op.drop_index(op.f('ix_forum_upvotes_thread_id'), table_name='forum_upvotes')
    op.drop_table('forum_upvotes')
    op.drop_index(op.f('ix_forum_posts_thread_id'), table_name='forum_posts')
    op.drop_index(op.f('ix_forum_posts_author_token'), table_name='forum_posts')
    op.drop_table('forum_posts')
    op.drop_index(op.f('ix_forum_threads_slug'), table_name='forum_threads')
    op.drop_index(op.f('ix_forum_threads_mod_id'), table_name='forum_threads')
    op.drop_index(op.f('ix_forum_threads_author_token'), table_name='forum_threads')
    op.drop_table('forum_threads')
    # ### end Alembic commands ###
