"""forum reactions

Revision ID: c75b72ec2554
Revises: 0b57a5639ff9
Create Date: 2026-05-22 21:42:27.758445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c75b72ec2554'
down_revision: Union[str, Sequence[str], None] = '0b57a5639ff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_reactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('voter_token', sa.String(length=64), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['forum_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['forum_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'voter_token', 'emoji', name='uq_reaction_post_voter_emoji')
    )
    op.create_index(op.f('ix_forum_reactions_post_id'), 'forum_reactions', ['post_id'], unique=False)
    op.create_index(op.f('ix_forum_reactions_thread_id'), 'forum_reactions', ['thread_id'], unique=False)
    op.create_index(op.f('ix_forum_reactions_voter_token'), 'forum_reactions', ['voter_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forum_reactions_voter_token'), table_name='forum_reactions')
    op.drop_index(op.f('ix_forum_reactions_thread_id'), table_name='forum_reactions')
    op.drop_index(op.f('ix_forum_reactions_post_id'), table_name='forum_reactions')
    op.drop_table('forum_reactions')
    # ### end Alembic commands ###
