"""mod_changelogs table

Revision ID: da41129f54b6
Revises: 0b899d72a3cd
Create Date: 2026-05-22 14:48:23.704765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da41129f54b6'
down_revision: Union[str, Sequence[str], None] = '0b899d72a3cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mod_changelogs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mod_id', sa.BigInteger(), nullable=False),
    sa.Column('post_id', sa.String(length=32), nullable=False),
    sa.Column('headline', sa.String(length=256), nullable=True),
    sa.Column('author_name', sa.String(length=128), nullable=True),
    sa.Column('author_profile_url', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mod_id'], ['mods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    op.create_index(op.f('ix_mod_changelogs_mod_id'), 'mod_changelogs', ['mod_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mod_changelogs_mod_id'), table_name='mod_changelogs')
    op.drop_table('mod_changelogs')
    # ### end Alembic commands ###
